catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create_book/', views.BookCreate.as_view(), name='create_book'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('vip_view/', view=views.vipView, name='vipView'),
    path('signup/', view=views.SignupView.as_view(), name='signup'),
    path('profile/', views.BorrowedBooksView.as_view(), name='profile')

]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
import uuid
from django.db import models
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author',
                               on_delete=models.SET_NULL,
                               null=True)
    summary = models.CharField(max_length=600)
    isbn = models.CharField('ISBN', max_length=13, unique=True)

    genre = models.ManyToManyField(Genre)

    language = models.ForeignKey('Language', on_delete=models.SET_NULL,
                                 null=True)

    def __str__(self):
        return f"Book Title: {self.title}\nAuthor: {self.author}\nISBN: {self.isbn}\nSummary: {self.summary}"

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})


class Language(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True,
                          default=uuid.uuid4)
    book = models.ForeignKey('Book', on_delete=models.RESTRICT,
                             null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    # Link borrowed book to user
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL,
                                 null=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='m')

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f"Instance Summary: {self.id}({self.book.title})"

catalog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from .models import Book, Author, BookInstance, Genre, Language
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

# Create your views here.


def index(request):

    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_available = BookInstance.objects.filter(
        status__exact='a').count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available
    }

    return render(request, 'catalog/index.html', context=context)


class BookCreate(LoginRequiredMixin, CreateView):  # book_form.html
    model = Book
    fields = '__all__'


class BookDetail(DetailView):
    model = Book


@login_required
def vipView(request):
    return render(request, 'catalog/vipView.html')

# -----------------------------------------
#           Registration Form
# -----------------------------------------


class SignupView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'catalog/signup.html'


# -----------------------------------------
#           Show Borrowed Books View
# -----------------------------------------
class BorrowedBooksView(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = 'catalog/profile.html'
    paginate_by = 5  # Books per page

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user)

catalog/templates/catalog/book_detail.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title-block %}
<title>Detail</title>
{% endblock title-block %}

<!-- prettier-ignore -->
{% block body-block %}
<div class="container">
  <h1>Book Detail</h1>
  <div>{{book}}</div>
</div>
{% endblock body-block %}

catalog/templates/catalog/book_form.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title-block %}
<title>Create Book</title>
{% endblock title-block %}

<!-- prettier-ignore -->
{% block body-block %}
<div class="container">
  <h1>Create New Book</h1>
  <form method="POST">
    {% csrf_token %}
    <!-- prettier-ignore -->
    {{form.as_p}}
    <input class="btn btn-primary" type="submit" value="Create Book" />
  </form>
</div>
{% endblock body-block %}

catalog/templates/catalog/index.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title-block %}
<title>Index</title>
{% endblock title-block %}

<!-- prettier-ignore -->
{% block body-block %}
<div class="container">
  <h1>Library Summary</h1>
  <!-- prettier-ignore -->
  {% if user.is_authenticated %}
  <p>Welcome <strong>{{user.get_username}}</strong>, you are logged in 😀</p>
  <a class="btn btn-danger" href="{% url 'logout' %}?next={{request.path}}"
    >Click to logout</a
  >

  {% else %}
  <p>Hey stranger! You are not logged in 😔</p>
  <a class="btn btn-success" href="{% url 'login' %}?next={{request.path}}"
    >Click to Login</a
  >
  {% endif %}
  <div>
    <ul>
      <li>Num Books: {{num_books}}</li>
      <li>Num of Instances: {{num_instances}}</li>
      <li>Num of Instances Available: {{num_instances_available}}</li>
    </ul>
  </div>
</div>
{% endblock body-block %}

catalog/templates/catalog/profile.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title-block %}
<title>Borrowed Books</title>
{% endblock title-block %}

<!-- prettier-ignore -->
{% block body-block %}
<h1>Welcome <strong>{{user.get_username}}</strong> to your profile</h1>
<div class="container">
  <h2>Borrowed Books</h2>
  <div>
    <ul>
      <!-- prettier-ignore -->
      {% for book in bookinstance_list %}
      <li>{{book}}</li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock body-block %}

catalog/templates/catalog/signup.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title-block %}
<title>New User</title>
{% endblock title-block %}

<!-- prettier-ignore -->
{% block body-block %}
<div class="container">
  <h1>Registration Form</h1>
  <form method="POST">
    {% csrf_token %}
    <!-- prettier-ignore -->
    {{form.as_p}}
    <input class="btn btn-primary" type="submit" value="Signup" />
  </form>
</div>
{% endblock body-block %}

catalog/templates/catalog/vipView.html
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block title-block %}
<title>Index</title>
{% endblock title-block %}

<!-- prettier-ignore -->
{% block body-block %}
<div class="container">
  <h1 style="color: red">Logged In Users Only</h1>
  <p>This page was made with a private Function decorator</p>
</div>
{% endblock body-block %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <!-- prettier-ignore -->
    {% block title-block %}
    <title>Document</title>
    {% endblock title-block %}
  </head>
  <body>
    <!-- prettier-ignore -->
    {% block body-block %}
    {% endblock body-block %}

    <!-- Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
      crossorigin="anonymous"
    ></script>
  </body>
</html>